#!/usr/bin/env bash
echo "============================================"
echo "   GitHub 命令行教程 - Git Bash 窗口"
echo "============================================"
echo ""
echo "下面会用真实命令操作 C:\\temp\\Hermes\\my-project 这个文件夹"
echo "每一步都会暂停，你看清楚了按回车继续"
echo ""
read -p "按回车开始..."

cd /c/temp/Hermes/my-project

echo ""
echo "============================================"
echo "  STEP 1: git init"
echo "  作用：让这个文件夹变成 git 仓库（装记录仪）"
echo "============================================"
read -p "按回车执行 git init..."
echo ""
git init
echo ""
echo "↑ 看到 Initialized empty Git repository 就是成功了"
echo ""
read -p "按回车继续..."

echo ""
echo "============================================"
echo "  STEP 2: git add ."
echo "  作用：把文件放进 git 的待传清单"
echo "============================================"
read -p "按回车执行 git add ."
echo ""
git add .
echo ""
echo "↑ 没有报错就是加好了"
echo ""
read -p "按回车继续..."

echo ""
echo "============================================"
echo "  STEP 3: git commit -m"
echo "  作用：拍一张快照（像游戏存档）"
echo "============================================"
read -p "按回车执行 git commit..."
echo ""
git commit -m "第一次提交：我的第一个仓库"
echo ""
echo "↑ 看到 [master (root-commit)] 就是存档成功了"
echo ""
read -p "按回车继续..."

echo ""
echo "============================================"
echo "  STEP 4: git log"
echo "  作用：看存档列表"
echo "============================================"
read -p "按回车执行 git log..."
echo ""
git log --oneline
echo ""
echo "↑ 那串数字就是这次提交的存档编号"
echo ""
echo "============================================"
echo "  本地流程全部演示完毕！"
echo "  最后一步 git push 需要你先在网页上建好仓库"
echo "============================================"
read -p "按回车关闭窗口..."